# Generated by Django 3.2 on 2023-05-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='genres',
            name='titles',
            field=models.ManyToManyField(null=True, related_name='titles', to='reviews.Titles'),
        ),
    ]
