# Generated by Django 3.2 on 2023-05-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='reviews.categories'),
        ),
    ]
