# Generated by Django 3.2 on 2023-05-26 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230526_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(error_messages={'validators': 'нельзя добавлять произведения из будущего :)'}, validators=[django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
