# Generated by Django 3.2 on 2023-05-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
